# 1 "app.js"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "app.js"
# 1 "utils.js" 1


# 1 "assert.js" 1




 function __error(message, file, line) {
  throw new Error(message + "(" + file + ":" + line + ")");
 }
# 4 "utils.js" 2

var Utils = {
 logger : function(message) {
  do { if(!(typeof message === "string")) { __error("assertion failed: " + "typeof message === \"string\"" + " = " + (typeof message === "string"), "utils.js", 7); } } while(false);
  console.log(message);
 }
};
# 2 "app.js" 2

Utils.logger("Hello world");
